FROM golang:1.24 AS build

RUN useradd -u 10001 dimo

WORKDIR /build
COPY . ./


RUN go mod tidy
RUN make build

FROM busybox AS final

LABEL maintainer="DIMO <hello@dimo.zone>"

WORKDIR /

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /build/bin/sample-enclave-api /

USER dimo

EXPOSE 8080
EXPOSE 8888

CMD /sample-enclave-api
