name: build-enclave-image-dev
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-app:
    name: build-app
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push enclave app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          load: false
          platforms: linux/amd64
          tags: dimozone/sample-enclave-runtime:${{ steps.slug.outputs.sha7 }}, dimozone/sample-enclave-runtime:latest

  build-enclave:
    name: build-enclave
    runs-on: [self-hosted]
    needs: build-app
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push enclave app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/enclave-runner/Dockerfile
          push: true
          load: false
          build-args: |
            ENCLAVE_NAME=sample-enclave-runtime
            ENCLAVE_TAG=${{ steps.slug.outputs.sha7 }}
            ENCLAVE_IMAGE=dimozone/sample-enclave-runtime
          platforms: linux/amd64
          tags: dimozone/sample-enclave-app:${{ steps.slug.outputs.sha7 }}, dimozone/sample-enclave-app:latest

      - name: Update image version
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: "charts/sample-enclave-api/values.yaml"
          value: ${{ steps.slug.outputs.sha7 }}
          branch: main
          message: "Update Image Version to ${{ steps.slug.outputs.sha7 }}"
          changes: |
            {
              "charts/sample-enclave-api/values.yaml": {
                "enclave.image.tag": ${{ steps.slug.outputs.sha7 }},
                "web.image.tag": ${{ steps.slug.outputs.sha7 }}
            }
