name: build-enclave-image-prod
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build-app:
    name: build-runtime
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Build and push enclave app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/runtime-dockerfile
          push: true
          load: false
          platforms: linux/amd64
          tags: dimozone/sample-enclave-runtime:${{steps.tag.outputs.tag}}, dimozone/sample-enclave-runtime:latest

  build-enclave:
    name: build-enclave
    runs-on: [self-hosted,enclave]
    needs: build-app
    container:
      image: dimozone/nitro-enclave-builder:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      volumes:
        - ${{ github.workspace }}/build/output:/build/output
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Build enclave
        run: nitro-cli build-enclave --docker-uri dimozone/sample-enclave-runtime:${{steps.tag.outputs.tag}} --output-file /bin/sample-enclave-app.eif
      - uses: actions/upload-artifact@v3
        with:
          name: sample-enclave-app
          path: ${{ github.workspace }}/bin/sample-enclave-app.eif

  build-final-image:
    # The type of runner that the job will run on
    name: build-final-image
    runs-on: [self-hosted]
    needs: build-enclave
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
 
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      
      - uses: actions/download-artifact@v3
        with:
          name: sample-enclave-app
          path: ${{ github.workspace }}/bin/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/enclave-dockerfile
          push: true
          platforms: linux/amd64
          tags: dimozone/sample-enclave-app:${{steps.tag.outputs.tag}}, dimozone/sample-enclave-app:latest

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: "charts/sample-enclave-api/values.yaml"
          propertyPath: "enclave.image.tag"
          value: ${{steps.tag.outputs.tag}}
          branch: main
          message: "Update Image Version to ${{steps.tag.outputs.tag}}"
