name: buildpushdev
on:
  push:
    branches:
      - main
jobs:
  build:
    name: buildpushdev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/dockerfile
          push: true
          platforms: linux/amd64
          tags: dimozone/sample-enclave-api:${{ steps.slug.outputs.sha7 }}, dimozone/sample-enclave-api:latest


