name: buildpushdev-bridge
on:
  push:
    branches:
      - main
env:
  APP_NAME: enclave-bridge
jobs:
  build:
    name: buildpushdev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/enclave-bridge/Dockerfile
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          platforms: linux/amd64
          tags: dimozone/${{ env.APP_NAME }}:${{ steps.slug.outputs.sha7 }}, dimozone/${{ env.APP_NAME }}:latest
