name: build-enclave-image-dev
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: sample-enclave

jobs:
  build-app:
    name: build-app
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push enclave app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          load: false
          platforms: linux/amd64
          tags: dimozone/${{ env.APP_NAME }}-runtime:${{ steps.slug.outputs.sha7 }}, dimozone/${{ env.APP_NAME }}-runtime:latest

  build-enclave:
    name: build-enclave
    runs-on: [self-hosted]
    needs: build-app
    container:
      image: dimozone/nitro-enclave-builder:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      volumes:
        - /node20217:/node20217
        - /node20217:/__e/node20
    steps:
      - name: Install dependencies
        run: yum install -y curl git tar gunzip xz wget
      - name: Print GLIBC version
        run: ldd --version
      - name: Install Node.js 20 glibc2.17
        run: |
          curl -LO https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node
      - uses: actions/checkout@v4
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Create bin directory
        run: mkdir -p bin
      - name: Build enclave
        run: nitro-cli build-enclave --docker-uri dimozone/${{ env.APP_NAME }}-runtime:${{ steps.slug.outputs.sha7 }} --output-file bin/${{ env.APP_NAME }}.eif
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}
          path: bin/${{ env.APP_NAME }}.eif

  build-final-image:
    # The type of runner that the job will run on
    name: build-final-image
    runs-on: [self-hosted]
    needs: build-enclave
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
 
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}
          path: bin/${{ env.APP_NAME }}.eif

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/enclave/Dockerfile
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          push: true
          platforms: linux/amd64
          tags: dimozone/${{ env.APP_NAME }}-enclave:${{ steps.slug.outputs.sha7 }}, dimozone/${{ env.APP_NAME }}-enclave:latest


      - name: Update image version
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: "charts/${{ env.APP_NAME }}-api/values.yaml"
          value: ${{ steps.slug.outputs.sha7 }}
          branch: main
          message: "Update Image Version to ${{ steps.slug.outputs.sha7 }}"
          changes: |
            {
              "enclave.image.tag": ${{ steps.slug.outputs.sha7 }},
              "web.image.tag": ${{ steps.slug.outputs.sha7 }}
            }
